In [1]:
import torch

In [2]:
x = torch.empty(2,2,2,3)
print(x)

tensor([[[[9.2755e-39, 1.0837e-38, 8.4490e-39],
          [8.9082e-39, 8.9082e-39, 4.1328e-39]],

         [[9.2756e-39, 8.9082e-39, 9.9184e-39],
          [9.0000e-39, 1.0561e-38, 1.0653e-38]]],


        [[[4.1327e-39, 8.9082e-39, 9.8265e-39],
          [9.4592e-39, 1.0561e-38, 1.0653e-38]],

         [[1.0469e-38, 9.5510e-39, 1.0378e-38],
          [8.9082e-39, 1.0653e-38, 1.1204e-38]]]])


In [3]:
x1 = torch.ones(2,2, dtype=torch.float16)
print(x1)
print(x1.dtype)
print(x1.size())

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)
torch.float16
torch.Size([2, 2])


In [4]:
x2 = torch.tensor([2.5, 0.1]) 
print(x2)

tensor([2.5000, 0.1000])


In [5]:
t1 = torch.rand(2,2)
t2 = torch.rand(2,2)
print(t1)
print(t2)

tensor([[0.6348, 0.2027],
        [0.6874, 0.6964]])
tensor([[0.3473, 0.6058],
        [0.9336, 0.8834]])


In [6]:
#z = t1 + t2
z = torch.add(t1,t2)
print(z)

tensor([[0.9821, 0.8085],
        [1.6210, 1.5799]])


In [7]:
t2.add_(t1)
print(t2)

tensor([[0.9821, 0.8085],
        [1.6210, 1.5799]])


In [8]:
#z = t1-t2
z1 = torch.sub(t1,t2)
print(z1)

tensor([[-0.3473, -0.6058],
        [-0.9336, -0.8834]])


In [9]:
#z = t1*t2 
z2 = torch.mul(t1,t2)
print(z2)

tensor([[0.6235, 0.1639],
        [1.1144, 1.1003]])


In [10]:
t2.mul_(t1)

tensor([[0.6235, 0.1639],
        [1.1144, 1.1003]])

In [11]:
#z = t1/t2
z3 = torch.div(t1,t2)
print(z3)

tensor([[1.0182, 1.2369],
        [0.6169, 0.6330]])


In [12]:
z4 =  torch.rand(5,3)
print(z4)
print(z4[:, 0])

tensor([[0.7948, 0.9898, 0.2955],
        [0.1230, 0.9752, 0.0979],
        [0.9278, 0.4601, 0.1212],
        [0.4092, 0.7441, 0.1984],
        [0.2472, 0.9023, 0.8182]])
tensor([0.7948, 0.1230, 0.9278, 0.4092, 0.2472])


In [13]:
print(z4[1, :])

tensor([0.1230, 0.9752, 0.0979])


In [14]:
print(z4[1, 1].item())

0.9751580953598022


In [15]:
z5 =  torch.rand(4,4)
print(z5)
z5_ =z5.view(16) 
print(z5_)

tensor([[0.3483, 0.1524, 0.8536, 0.7753],
        [0.2021, 0.2508, 0.0708, 0.7656],
        [0.5109, 0.4282, 0.2245, 0.8502],
        [0.0572, 0.6602, 0.7345, 0.0198]])
tensor([0.3483, 0.1524, 0.8536, 0.7753, 0.2021, 0.2508, 0.0708, 0.7656, 0.5109,
        0.4282, 0.2245, 0.8502, 0.0572, 0.6602, 0.7345, 0.0198])


In [16]:
z5_ =z5.view(-1,8)
print(z5_.size())

torch.Size([2, 8])


In [17]:
import numpy as np

In [18]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [19]:
b= a.numpy()
print(type(b))

<class 'numpy.ndarray'>


In [20]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [21]:
arr = np.ones(5)
print(arr)
arr1 = torch.from_numpy(arr)
print(arr1)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [22]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device )
    y = torch.ones(5)
    y= y.to(device)
    z = x+y
    print(z)

tensor([2., 2., 2., 2., 2.], device='cuda:0')
