In [1]:
import torch
import torch.nn as nn
import numpy as np

In [5]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x), axis=0)

x = np.array([2.0, 1.0, 0.1])

outputs = softmax(x)

print('softmax numpy array:',outputs)

softmax numpy array: [0.65900114 0.24243297 0.09856589]


In [7]:
x = torch.tensor([2.0, 1.0, 0.1])
outputs = torch.softmax(x, dim=0) 
print(outputs)

tensor([0.6590, 0.2424, 0.0986])


In [8]:
def cross_entropy(actual, predicted):
    EPS = 1e-15
    predicted = np.clip(predicted, EPS, 1 - EPS)
    loss = -np.sum(actual * np.log(predicted))
    return loss # / float(predicted.shape[0])

In [9]:
# y must be opne hot encoding 
Y = np.array([1, 0, 0])
# y_pred has probabilities
Y_pred_good = np.array([0.7, 0.2, 0.1])
Y_pred_bad = np.array([0.1, 0.3, 0.6])
l1 = cross_entropy(Y, Y_pred_good)
l2 = cross_entropy(Y, Y_pred_bad)
print(f'Loss1 numpy: {l1:.4f}')
print(f'Loss2 numpy: {l2:.4f}')


Loss1 numpy: 0.3567
Loss2 numpy: 2.3026


In [20]:
loss = nn.CrossEntropyLoss()

y = torch.tensor([0])

# input is of size nSamples x nClasses = 1 x 3
# y_pred (=input) must be raw, unnormalizes scores (logits) for each class, not softmax
y_pred_good = torch.tensor([[2.0, 1.0, 0.1]])
y_pred_bad = torch.tensor([[0.5, 2.0, 0.3]])
l1 = loss(y_pred_good, y)
l2 = loss(y_pred_bad, y)

print(f'PyTorch Loss1: {l1.item():.4f}')
print(f'PyTorch Loss2: {l2.item():.4f}')

PyTorch Loss1: 0.4170
PyTorch Loss2: 1.8406


In [21]:
_, predictions_1 = torch.max(y_pred_good,1)
_, predictions_2 = torch.max(y_pred_bad,1)
print(predictions_1)
print(predictions_2)

tensor([0])
tensor([1])


In [22]:
y1 = torch.tensor([2, 0, 1])
# input is of size nSamples x nClasses = 3 x 3
y_pred_good_1 = torch.tensor([[0.1, 1.0, 2.1], [2.0, 1.0, 0.1], [2.0, 3.0, 0.1]])
y_pred_bad_1 = torch.tensor([[2.1, 1.0, 2.1], [0.1, 1.1, 2.1], [1.0, 3.0, 0.1]])

l1 = loss(y_pred_good_1, y1)
l2 = loss(y_pred_bad_1, y1)

print(f'PyTorch Loss1: {l1.item():.4f}')
print(f'PyTorch Loss2: {l2.item():.4f}')

_, predictions_3 = torch.max(y_pred_good_1,1)
_, predictions_4 = torch.max(y_pred_bad_1,1)
print(predictions_3)
print(predictions_4)

PyTorch Loss1: 0.3846
PyTorch Loss2: 1.1430
tensor([2, 0, 1])
tensor([2, 2, 1])
