In [1]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.7835,  0.6443, -1.4014], requires_grad=True)


In [4]:
y = x+ 2
print(y)

tensor([2.8648, 2.9601, 2.7667], grad_fn=<AddBackward0>)


In [5]:
z = y*y*2
z = z.mean()
print(z)

tensor(16.4161, grad_fn=<MeanBackward0>)


In [6]:
z.backward() # dz/dx

In [8]:
print(x.grad)

tensor([3.8197, 3.9468, 3.6889])
